title: арсли
author: arslee
email: me@arslee.dev
description: >
  ку, это тестовая страниччк арсли =)

# social links
twitter_username: arslee_
github_username: arslee07
telegram_username: arslee

skin: dark

show_excerpts: true
theme: minima

plugins:
 - jekyll-seo-tag
